### ISSUE TITLE
Over allocation of memory in certain invalid syntax scenarios

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#113]
**Describe the bug**

Ref: denoland/deno#9650

Deno version: 1.7.5

**Input Code**

```ts
export class X {

  constructor() {
  }
  bad(target :number) {
    const d = 1;
    const min = 0;
    const max = 100;
    console.log("x", `duration ${d} not in range - ${min} ≥ ${d} && ${max} ≥ ${d}`),;
  }
}
```

**Expected Output**

A noop

**Actual Output**

```
memory allocation of 18446744073709551615 bytes failed
[1]    8481 abort      deno fmt
```

**Comment by dsherret** [comment]
Thanks. It should be a diagnostic here. Seems like it's subtracting with overflow in dprint-core somewhere:

```rust
thread 'test_specs' panicked at 'attempt to subtract with overflow', C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\dprint-core-0.35.1\src\formatting\utils\string_utils.rs:74:37
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:495
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\panicking.rs:50
   3: dprint_core::formatting::utils::string_utils::get_range_text_highlight
             at C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\dprint-core-0.35.1\src\formatting\utils\string_utils.rs:74
   4: dprint_core::formatting::utils::string_utils::format_diagnostic
             at C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\dprint-core-0.35.1\src\formatting\utils\string_utils.rs:40
   5: dprint_plugin_typescript::swc::parse_swc_ast::format_swc_error
             at .\src\swc\parse_swc_ast.rs:119
```

I'm not sure why the deno message says it allocates 18446744 terabytes of memory 😅

**Comment by dsherret** [comment]
This occured due to the `≥` multi-byte character. I was correctly using the character position for the end index, but accidentally used the byte index for the start index, which caused a start index > end index.
