### ISSUE TITLE
Panic when formatting certain type expressions

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#121]
**Describe the bug**

Deno version: 1.8.1

**Input Code**

```ts
type T =
  | unknown
  { } & unknown;
```

**Expected Output**

Something that doesn't panic.

**Actual Output**

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.41.0/src/parsing/swc/flatten_binary_expr.rs:22:94
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Panic formatting: <file>', cli/tools/fmt.rs:393:5
```

Ref: denoland/deno#9887

**Comment by dsherret** [comment]
Fixed by surfacing the diagnostic for this syntax error.
